# -*- mode: ruby -*-
# vi: set ft=ruby :

Vagrant.configure(2) do |config|

  config.vm.box = "bento/centos-7.1"

  config.vm.define "node1" do |node1|
    node1.vm.network "private_network", ip: "192.168.33.10"
    node1.vm.hostname = "node1"
  end

  config.vm.provision "shell" do |s|
    s.inline = "
    sudo sed -i 's/node1 //' /etc/hosts;
    sudo sed -i '\$a192.168.33.10 biggis.dev.net.node1' /etc/hosts;
    hostname biggis.dev.net.node1;
    wget --no-cookies --no-check-certificate --header 'Cookie: gpw_e24=http%3A%2F%2Fwww.oracle.com%2F; oraclelicense=accept-securebackup-cookie' http://download.oracle.com/otn-pub/java/jdk/8u60-b27/jre-8u60-linux-x64.rpm;
    yum -y localinstall jre-8u60-linux-x64.rpm;
    iptables -F;
    service iptables save;
    rpm -Uvh http://archive.cloudera.com/cdh4/one-click-install/redhat/6/x86_64/cloudera-cdh-4-0.x86_64.rpm;
    yum -y install zookeeper zookeeper-server;
    sudo -u zookeeper zookeeper-server-initialize --myid=1;
    sudo service zookeeper-server start;
    rpm -Uvh http://repos.mesosphere.io/el/7/noarch/RPMS/mesosphere-el-repo-7-1.noarch.rpm;
    yum -y install mesos;
    #mesos-init-wrapper master &;
    sudo service mesos-master start;
    sudo service mesos-slave start;
    "
    s.privileged = true
  end

end
