# -*- mode: ruby -*-
# vi: set ft=ruby :

Vagrant.configure(2) do |config|

  config.vm.box = "bento/centos-7.1"

  config.vm.define "node1" do |node1|
    node1.vm.network "private_network", ip: "192.168.33.10"
    node1.vm.hostname = "node1"
  end

  config.vm.provision "shell" do |s|
    s.inline = "
    sudo sed -i 's/node1 //' /etc/hosts;
    sudo sed -i '\$a192.168.33.10 biggis.dev.net.node1' /etc/hosts;
    sudo sed -i 's/node1/biggis.dev.net.node1/g' /etc/hostname
    sudo hostname biggis.dev.net.node1;
    "
    s.privileged = true
  end

end
